### PR TITLE
Fix dropdown menu position in plugin card

### PR DESCRIPTION
**Pull request by mkz212**

### CODE REVIEW

**Comment by bwp91** [comment]
Screenshot 2023-12-10 at 15 36 53

Here seems too far away from the menu icon

**Comment by mkz212** [comment]
@bwp91 

I think you need also add width to dropdown. Try now (I updated code).

**Comment by bwp91** [comment]
I managed to get pretty much the same behaviour here simply by changing this `placement` to `left`.

https://github.com/homebridge/homebridge-config-ui-x/blob/7c69b5a22ad83f872e76fe01d792ba55fe2c2b2d/ui/src/app/modules/plugins/plugin-card/plugin-card.component.html#L97

Seems like an easier way of getting this behaviour?

**Comment by mkz212** [comment]
👍

**Pull request closed without merging**
