### PR TITLE
Update power-options.component.html

### PR DESCRIPTION
**Pull request by mkz212**
From:
Zrzut ekranu 2023-12-31 o 06 49 44

To:
Zrzut ekranu 2023-12-31 o 06 49 04

### CODE REVIEW

**Comment by bwp91** [comment]
how do these changes look in a browser the same width as your 'from' screenshot?

**Comment by mkz212** [comment]
They look good.

**Comment by bwp91** [comment]
please could you show a screenshot?

**Comment by mkz212** [comment]
I don't have a computer with me. And I would have to reinsulate this to the inspector. It's just that the buttons are 85% wide instead of 75 and are a little higher. And that's it. It is a small change.

**Comment by bwp91** [comment]
no problem, i have rebased onto alpha, this could be a change we make in a future version 👍

**Comment by bwp91** [comment]
thanks @mkz212

**Pull request merged**
