### PR TITLE
Replace problematic tooltip

### PR DESCRIPTION
**Pull request by mkz212**
Not so beautiful but does not make problems and disappears on mobile devices.

Zrzut ekranu 2023-12-1 o 15 27 27

### CODE REVIEW

**Comment by bwp91** [comment]
I'm not a fan of this, I think I would rather the tooltip stay visible, or we find a different solution. What do you think @donavanbecker ?

**Comment by mkz212** [comment]
Easies solution, if you want current tooltip, is detect if device is mobile (you have function for this) and if so, do not display tooltip. 

First option is disableTooltip. See https://ng-bootstrap.github.io/#/components/tooltip/api . 

Second option is using ngif to display / hide element - here every element will be doubled - one with tooltip and one without.

**Comment by donavanbecker** [comment]
Yeah I would rather disable for mobile.

**Comment by bwp91** [comment]
Let's close this and we can look into another potential solution of globally disabling tooltip on mobile?

**Pull request closed without merging**
