### PR TITLE
hide tooltip on mobile

### PR DESCRIPTION
**Pull request by mkz212**
@bwp91 can you try this?

### CODE REVIEW

**Comment by bwp91** [comment]
Hi @mkz212 do you have the UI running locally? is this a confirmed fix?

**Comment by mkz212** [comment]
No I don't have locally.

This is the official way from: [https://ng-bootstrap.github.io/#/components/tooltip/api](https://ng-bootstrap.github.io/#/components/tooltip/api)

So if it doesn't work, it's probably that only solution will be completely hiding the tooltip on small devices (with css).

**Comment by mkz212** [comment]
Alternatively:

```
triggers="manual"
#t="ngbTooltip" 
(mouseenter)="t.open()" 
(mouseleave)="t.close()
```

**Comment by mkz212** [comment]
Or something like:

`[disableTooltip]="'(window.screen.width < 768)'">`

**Comment by mkz212** [comment]
On the Internet I read a lot of posts about the fact that many people do not work as it should (does not disappear Or appears on the phone even though it shouldn't), which is why they combine.

**Comment by donavanbecker** [comment]
We will hold this one until next version.

**Comment by mkz212** [comment]
I see it didn't help. As I said - a lot of people have a problem with it. Even on the official website it doesn't work as it should (hiding).

**Pull request closed without merging**
