### PR TITLE
Port translation

### PR DESCRIPTION
**Pull request by mkz212**
Change to: 

Port: 12345

### CODE REVIEW

**Comment by donavanbecker** [comment]
Do we want colons `:` after each "port" word, in each language?

**Comment by mkz212** [comment]
I proposed it before and I think it looks good.

**Comment by donavanbecker** [comment]
Can you please at it? I will then Merge.

**Comment by mkz212** [comment]
But what to do? Remove `:` ?

**Comment by donavanbecker** [comment]
I think add it, not?

**Comment by mkz212** [comment]
I completely don't understand? What should I do? Specifically please..

**Comment by donavanbecker** [comment]
add colon `:` after Port

**Comment by mkz212** [comment]
But I added `:` after Port

**Comment by donavanbecker** [comment]
Sorry, There were some that were missing it. Just reviewed now and saw all had them. Thanks!

**Review by donavanbecker — APPROVED** [review]

**Pull request merged**
