### PR TITLE
Restart server with confirmation. Username next to Logout. 

### PR DESCRIPTION
**Pull request by mkz212**
- Added confirmation (do you want to restart the server?) After pressing the power icon directly on the bar (as in the menu).
- Added username next to logout:
Zrzut ekranu 2023-11-8 o 15 07 52

- Minor corrections in pl language

### CODE REVIEW

**Comment by bwp91** [comment]
Sorry Im gonna use this PR to ask a couple of different things!

1. Could this menu in desktop view be moved so the top lines up with the botton of the main top menu? (ignore the restart tooltip!)

Screenshot 2023-11-08 at 18 53 31


2. i wonder if these dropdowns need a slightly darker background colour to make it clearer amongst the other things behind it?
Screenshot 2023-11-08 at 18 53 52

**Comment by mkz212** [comment]
Yes. I will make PR.

Like this (menu position and dropdown color)?:


Zrzut ekranu 2023-11-8 o 20 19 53

**Comment by mkz212** [comment]
@bwp91 Ok, I just created two PR with this.

**Comment by mkz212** [comment]
What do you think about removing the underlining of links?

Zrzut ekranu 2023-11-8 o 20 44 40


Instead of the current one:

Zrzut ekranu 2023-11-8 o 20 45 34

**Comment by mkz212** [comment]
And what do You think about this PR? 

- confirmation modal to restart sever, in dropdown menu already is so it could be also after click on power icon in navbar. 

- username next to Logout in dropdown menu, E.G.: Logout - admin

**Review by donavanbecker — APPROVED** [review]

**Comment by donavanbecker** [comment]
@mkz212, Big issue with dark mode!

Screenshot 2023-11-08 at 10 27 14 PM

**Comment by donavanbecker** [comment]
Same with Light Mode Screenshot 2023-11-08 at 10 27 56 PM

**Comment by donavanbecker** [comment]
I have reverted these changes So please open a new PR with changes.

**Pull request merged**
