### PR TITLE
Update uk.json

### PR DESCRIPTION
**Pull request by xrust83**
I don't understand the context of these translations so translate them when I understand what is meant

"status.widget.label_network_activity.history_items": "History Items",
  "status.widget.label_network_activity.items": "items",

## :recycle: Current situation

*Describe the current situation. Explain current problems, if there are any. Be as descriptive as possible (e.g., including examples or code snippets).*

## :bulb: Proposed solution

*Describe the proposed solution and changes. How does it affect the project? How does it affect the internal structure (e.g., refactorings)?*

## :gear: Release Notes

*Provide a summary of the changes or features from a user's point of view. If there are breaking changes, provide migration guides using code examples of the affected features.*

## :heavy_plus_sign: Additional Information
*If applicable, provide additional context in this section.*

### Testing

*Which tests were added? Which existing tests were adapted/changed? Which situations are covered, and what edge cases are missing?*

### Reviewer Nudging

*Where should the reviewer start? what is a good entry point?*

### CODE REVIEW

**Comment by xrust83** [comment]
I, too, did not find a point among the translation
"Moved to Main Menu"
Знімок екрана 2024-08-03 о 18 11 06

**Comment by mkz212** [comment]
> I, too, did not find a point among the translation "Moved to Main Menu" Знімок екрана 2024-08-03 о 18 11 06

There is no such thing in the beta anymore.

**Comment by mkz212** [comment]
> I don't understand the context of these translations so translate them when I understand what is meant
> 
> "status.widget.label_network_activity.history_items": "History Items", "status.widget.label_network_activity.items": "items",
> 

Translate literally

**Comment by xrust83** [comment]
Ok. Ready

**Pull request merged**
