### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by jsiegenthaler**
Fixed a bunch of DE translation inconsistencies

### CODE REVIEW

**Comment by donavanbecker** [comment]
@jsiegenthaler, the first commit wasn't the best. Can you update your PR based off the updates that I just committed? and resolve conflicts on this PR?

**Comment by jsiegenthaler** [comment]
@donavanbecker Happy to fix this. Please advise which base branch you want me to compare against. I tried beta-4.53.0 but that doesn't look the best branch

**Comment by donavanbecker** [comment]
I updated it to the Google-translate branch

**Comment by jsiegenthaler** [comment]
I'll delete this PR for now and make a new PR at some later date

**Pull request closed without merging**
