### PR TITLE
Restart with confirmation

### PR DESCRIPTION
**Pull request by mkz212**
show modal with confirmation, like after click restart in dropdown menu

### CODE REVIEW

**Comment by donavanbecker** [comment]
are we going to have the same issue as `.57`? the code looks the same.

**Comment by mkz212** [comment]
I split the code into 3 PR: 
- language fixes
- confirmation
- add username to menu (i thikk that here i made previously mistake)

so maybe first add lang fix and confirmation and we will test it?

**Comment by donavanbecker** [comment]
okay all have been merged and upgraded with no issues so far. Should I merge this?

**Comment by mkz212** [comment]
Yes, add please. I think that problem was in username.

**Review by donavanbecker — APPROVED** [review]

**Comment by mkz212** [comment]
Works well.

**Comment by mkz212** [comment]
Hmm... wait....

**Comment by mkz212** [comment]
It showing modal to shutdown server - it should be to restart.

**Comment by donavanbecker** [comment]
can you confirm all are working good?

**Comment by mkz212** [comment]
No. 

We need to replace 

`shutdownServer()`

to 

`restartServer()`


Will you do it or should I do PR?

**Comment by donavanbecker** [comment]
done

**Comment by mkz212** [comment]
Thank You.

**Comment by donavanbecker** [comment]
FYI there does seem to be an issue with install of new plugins. Can you please take a look?

**Comment by donavanbecker** [comment]
Screenshot 2023-11-09 at 12 20 35 AM

**Comment by mkz212** [comment]
Hmm... It seems that nothing appears in this window - it's not about the fact that, for example, the text is invisible, but just as if nothing is happening there. In my PR there was rather nothing that would have any impact on it.

**Comment by donavanbecker** [comment]
Yeah not on this one but I think one of them?

**Comment by mkz212** [comment]
Changing theme - not solve problem. When I inspect this element it is just empty. It looks like nothing is happening there.Because if it was a display problem, the window would disappear after a while. I also wonder why the plugin update works well but the installation of the new one does not?

My PR was about:
- dropdown menu
- default layout on the status page + small widget fixes
- translations

I don't think anything will affect it. All the changes I proposed were only in the "ui" directory - I don't think he was responsible for installing plugins. But of course I will think, I will look, I will try to help.

**Comment by grzegorz914** [comment]
@donavanbecker 
on my side with latest beta.63 install new plugin working correct

**Comment by mkz212** [comment]
beta 63 - I have same problem as @donavanbecker mention

I have raspberry pi 4
Homebridge Image 1.0.41
Linux Bullseye
Node 20.9.0

**Comment by grzegorz914** [comment]
@mkz212 , @donavanbecker  strange, on my side all working as expected

macOS Sonoma
macMini M1
node 21.1.0
hb 1.7.0

**Comment by mkz212** [comment]
@donavanbecker And You? Maybe we will find a common point.

**Comment by mkz212** [comment]
@grzegorz914 

Do you see any more mistakes?

I think we've solved everything you've been writing about lately.:
- restart with confirmation
- scrollable homebridge widget 
- and other fixes in status page

**Comment by donavanbecker** [comment]
Still having issue on latest beta with docker.

Last thing I am trying to implement before releasing this version is child bridge restart, if anyone want to take what I have added so far....

**Comment by mkz212** [comment]
DOESN'T WORK ON:
- Raspberry Pi 4B
- Homebridge Image 1.0.41
- Linux Bullseye
- Node 20.9.0

WORK ON:
- macOS Sonoma
- macMini M1
- node 21.1.0
- hb 1.7.0

So I think that is not node or hb's fault.

**Comment by mkz212** [comment]
@donavanbecker When i try to install plugin via terminal:
Zrzut ekranu 2023-11-9 o 08 00 12

**Comment by grzegorz914** [comment]
@mkz212 
restart with confirmation - OK
scrollable widget - OK
another layout fixes - OK

one more thing, the pop up menu for plugins 3 dots need to be bound same as the pop up menu in navbar - always to the right side of popup menu
Zrzut ekranu 2023-11-9 o 07 59 15
Zrzut ekranu 2023-11-9 o 07 59 33

**Comment by mkz212** [comment]
@donavanbecker I found another mistake, it only happens in child bridge:

Zrzut ekranu 2023-11-9 o 08 03 46
Zrzut ekranu 2023-11-9 o 08 04 01

There is such a triangle next to 3 dots when you click on 3 dots.

**Comment by donavanbecker** [comment]
That only happens to the bottom item

**Comment by mkz212** [comment]
@donavanbecker 

If it is not to appear, you have to add to css:

```
.dropup .dropdown-toggle:after {
display:none;
}
```

**Comment by mkz212** [comment]
and this css is to bound to the right side (@grzegorz914  idea):

```
.card-body .dropdown-menu.show {
transform: translate(-200px, 30px) !important;
}
```

Zrzut ekranu 2023-11-9 o 08 31 09


But I don't think it's a good idea. Currently, the window adjusts dynamically. For example, on the mobile, in the last element when we click this window will appear above 3 dots:
Zrzut ekranu 2023-11-9 o 08 35 57

**Comment by mkz212** [comment]
Ok I made PR with a possible solution for it to be bounded to right and adjust automatically.

**Comment by mkz212** [comment]
@donavanbecker 

If I go into the search for a new plugin, strange things happen:

- empty fields appear at the bottom and in one plugin there is opened dropdown:
Zrzut ekranu 2023-11-9 o 13 56 45
- click on Install another version show empty modal:
Zrzut ekranu 2023-11-9 o 13 57 35
- command to install plugin via terminal still doesn't work:
Zrzut ekranu 2023-11-9 o 13 59 41

**Comment by donavanbecker** [comment]
We need to fix that.

**Comment by grzegorz914** [comment]
@mkz212 
very strange, on my side all is correct
image
image

**Comment by mkz212** [comment]
I checked it on different browsers (Safari and Firefox) And I have the same error on both. But it only occurs when installing a new plugin. In the view of the current plugins, everything works fine. If it works well for you, maybe it's a bug related to the device ? @donavanbecker @bwp91 Didn't you introduce anything related to the GLIBC and node error - something to detect system etc.?

In ui code there is one code responsible for the appearance of both: installed plug-ins and those to be installed. If there was an error here, it would be visible in both places, but this is not because the installed plug-ins are displayed correctly.

**Comment by mkz212** [comment]
The problem occurs when the plug-in list is too long. E.g. If I only have two results or 5, it's ok - I can install new plugin and the layout is ok. But even if I have long list installed plugin - there is no problem - problem only when search for new plugin!

But what does it have to do with installing a plug from the terminal command? You can't install the plugin there.

And why for @grzegorz914 all works fine?

**Comment by donavanbecker** [comment]
This resolved it for me! https://github.com/homebridge/homebridge-config-ui-x/pull/1673

**Comment by mkz212** [comment]
beta 66 still have this problem:
Zrzut ekranu 2023-11-9 o 16 23 58

**Comment by grzegorz914** [comment]
@mkz212 @donavanbecker if search for `camera` then result is 30 plugins and all is displayed correct but if search for `samsung` the result is same 30 plugins but only first 9 is displayed correct. Search other word like `apple` also display 30 plugins correct.

**Comment by donavanbecker** [comment]
Okay I can recreated.

**Comment by mkz212** [comment]
same here! 

camera - ok
samsung - problem
apple - ok

**Comment by donavanbecker** [comment]
must be a feature to push people to Apple? ;)

**Comment by mkz212** [comment]
I just checked and in 4.52.1 it is ok.

**Comment by donavanbecker** [comment]
pushing a potential fix that we found

**Comment by mkz212** [comment]
beta 67 still have this problem

**Comment by donavanbecker** [comment]
beta68 should fix it.

**Comment by donavanbecker** [comment]
@mkz212 are you on the homebridge discord?

**Comment by mkz212** [comment]
Finaly! Beta 68 fix it!

**Comment by mkz212** [comment]
but still problem installing plugin from terminal:

Zrzut ekranu 2023-11-9 o 16 58 22

**Comment by grzegorz914** [comment]
@donavanbecker @mkz212  b.68 fix for me too, in other things after update plugin running as child bridge I get possibility to restart only the child bridge but nothing happens after press the button on modal window.

**Comment by donavanbecker** [comment]
yeah that is a work in progress. Restart Homebridge should show as well right now.

**Comment by donavanbecker** [comment]
> but still problem installing plugin from terminal:
> 
> Zrzut ekranu 2023-11-9 o 16 58 22

if you are on hb-service you can do `npm install`

**Comment by donavanbecker** [comment]
@mkz212 seeing this on docker: 

image
 
and shouldn't be

**Comment by mkz212** [comment]
@donavanbecker Can you be a little more accurate? When do you see it? And why shouldn't it be? In the sense, there should be no restart option at all? Shouldn't there be confirmation?

**Comment by donavanbecker** [comment]
you can't restart the docker OS, you can however restart the container. we have reverted the restart back to just restarting homebridge for now.

**Comment by mkz212** [comment]
Aaaa... OK! Thank You. I have already corrected. I added PR. Now there is detection whether docker or not (as in the dropdown menu).

**Pull request merged**
