### PR TITLE
Changed spelling from Centre -> Center

### PR DESCRIPTION
**Pull request by justjam2013**
## :recycle: Current situation

Center was misspelled  😁

### CODE REVIEW

**Comment by NorthernMan54** [comment]
It is spelled correctly, you may just be in the wrong country!!! (LOL)

For Me and BWP it is correct

**Comment by bwp91** [comment]
i plan to rename the widget something less controversial before release 😂

**Comment by justjam2013** [comment]
"Organise Favourite Behaviour Calibre" widget. That should not cause any controversy whatever, as long as you don't pronounce "controversy" out loud. 🤣

**Comment by bwp91** [comment]
Closing as no longer needed

**Pull request closed without merging**
