### PR TITLE
plugin card next fix

### PR DESCRIPTION
**Pull request by mkz212**
Zrzut ekranu 2023-11-27 o 06 13 13
Zrzut ekranu 2023-11-27 o 06 13 32

### CODE REVIEW

**Comment by mkz212** [comment]
@donavanbecker did you merge this? and release alpha with this? because i dont see changes in alpha 53

**Comment by donavanbecker** [comment]
I did

**Comment by mkz212** [comment]
@donavanbecker So something went wrong because i dont have changes.

**Comment by mkz212** [comment]
Ok I will do PR again

**Pull request merged**
