### PR TITLE
Removed conditional for displaying search exit component

### PR DESCRIPTION
**Pull request by justjam2013**
## :recycle: Current situation

[Can't exit plugin Search mode when search term is empty #2248](https://github.com/homebridge/homebridge-config-ui-x/issues/2248)

## :bulb: Proposed solution

Always display search exit component.

Clicking the exit Search component when no search term provided causes the currently displayed plugins to be redisplayed. This behavior is no different than placing the cursor on the Search textbox and pressing enter with no search term specified.

## :gear: Release Notes

Removed conditional from display of search exit component.

### CODE REVIEW

**Comment by bwp91** [comment]
How about if the X is shown when displaying a list of searched for plugins (independent of what characters may or may not be in the search bar), and the X is hidden when showing your currently installed plugins?

**Comment by justjam2013** [comment]
Yes, your solution is perfect. Clarifying:

- the X is shown when displaying the result of a plugin search
   - the search term length is 0 ... N chars
   - the list of found plugins is 0 ... N plugins
- the X is hidden when showing your currently installed plugins

**Comment by bwp91** [comment]
i just pushed a change (hope you don't mind) let me know if it works for you

**Comment by justjam2013** [comment]
Looks good.

**Pull request merged**
