### PR TITLE
Add icons for shower head and water faucet valve types

### PR DESCRIPTION
**Pull request by justjam2013**
## :recycle: Current situation

Currently the Valve service type has icons for valve type 0 - Generic Valve and valve type 1 - Irrigation. To display valve type 2 - Shower Head and valve type 3 - Water Faucet, the UI reuses the icon for Generic Valve.

## :bulb: Proposed solution

Display distinct icons for Shower Head and Water Faucet valve types.

## :gear: Release Notes

Added SVG images for valve type 2 - Shower Head and valve type 3 - Water Faucet.
Modified html to display new icons for valve type 2 - Shower Head and valve type 3 - Water Faucet.

### Reviewer Nudging

Check SVG images.

### CODE REVIEW

**Comment by bwp91** [comment]
Hi @justjam2013 i like the new icons, how would you feel if they were the same colours as the existing generic valve icon, like this, rather than all black:

Existing generic icon:
Screenshot 2024-12-08 at 09 48 24

New icons:
Screenshot 2024-12-08 at 09 47 27
Screenshot 2024-12-08 at 09 47 45

**Comment by justjam2013** [comment]
I prefer your colored icons much better.

**Comment by justjam2013** [comment]
Should the valve irrigation icon get the same treatment?

Screenshot 2024-12-08 at 10 52 24 AM

**Comment by bwp91** [comment]
Screenshot 2024-12-08 at 11 27 28
Screenshot 2024-12-08 at 11 27 32
Screenshot 2024-12-08 at 11 29 41
Screenshot 2024-12-08 at 11 29 45
Screenshot 2024-12-08 at 11 30 04
Screenshot 2024-12-08 at 11 30 08
Screenshot 2024-12-08 at 11 31 22
Screenshot 2024-12-08 at 11 31 27

**Comment by justjam2013** [comment]
Yeah, love them!

**Comment by justjam2013** [comment]
BTW, I deleted the comment about the sprinkler icon, because I realized that it really shouldn't have been within the scope of this PR. I didn't want to create scope creep.

**Pull request merged**
