### PR TITLE
small change

### PR DESCRIPTION
**Pull request by mkz212**
small change

### CODE REVIEW

**Comment by donavanbecker** [comment]
@mkz212 Thank you for all of your work on make the UI look awesome!

Going forward we would like to get one PR per release to merge into beta for testing. All of these small little changes are causing GitHub Actions to slow down which then causes builds to fail.

We will hold this PR until next release. Our recommendation would be to run `homebridge-config-ui-x` local with Visual Studio Code. nodemon is your best friend with running it local. If you need help with getting it setup and running correctly please join the Homebridge discord server.

Once again thanks!

**Comment by mkz212** [comment]
I think that this PR is only left. So far I have run out of ideas ;)

**Comment by mkz212** [comment]
Also thank You @donavanbecker and @bwp91 for including all and for amazing job!

**Comment by donavanbecker** [comment]
@mkz212 sounds good. We can include it in this PR, but will not be pushing any betas until we have somethings on outside figured out first. We can then include this and release after much beta testing from Users :)

**Comment by donavanbecker** [comment]
@mkz212 feel free to reach out to us on discord.

**Comment by mkz212** [comment]
I don't insist, but it's just a small change, and it's actually been tested and it looked good. This is what we took to test if it causes the problem. In the sense it was already added and checked and it was ok. Then we removed it to see if it would help with this plug-in search and it didn't help, so that's not what caused the problem.

**Comment by donavanbecker** [comment]
Okay, I will merge. Any PRs after this though I will wait for next release. Okay?

**Review by donavanbecker — APPROVED** [review]

**Comment by mkz212** [comment]
Everything looks ok in beta 69! I think it's ready!

**Comment by donavanbecker** [comment]
Thanks @mkz212. We need to finish a few things on our side first and then will have a beta period. So be on the look out. Thanks!

**Comment by bwp91** [comment]
One more thing is bugging me

The tooltip does not disappear when opening modals

IMG_6664

is it possible to change this behaviour? @mkz212 i don’t think this has been caused by anything you have done, but if you are looking for stuff to do 😉

**Pull request merged**
