### PR TITLE
Added a Network widget

### PR DESCRIPTION
**Pull request by seidnerj**
It displays sent & received megabytes per second as well as a graph of the overall throughput per second.

### CODE REVIEW

**Comment by seidnerj** [comment]
I fixed the linting wrnings, can try to re-run now.

**Comment by seidnerj** [comment]
This seems to fail with something unrelated to the commits I have made, maybe it has to do with windows-latest now running on 2022? can someone please help?

**Comment by seidnerj** [comment]
Hmmm, fetching the network stats fails on Windows due to a timeout for some reason, can't figure out why - any help would be appreciated.

**Comment by seidnerj** [comment]
I tried replicating the issue that shows up in the windows tests using a Windows 11 VM but could not replicate it. Could someone help?

**Comment by seidnerj** [comment]
Okay, fixed. All tests have passed, see here: https://github.com/seidnerj/homebridge-config-ui-x/actions/runs/1855056483

**Comment by seidnerj** [comment]
Sorry for the all the mess, next time I'm going to work off of a feature branch and only merge to the fork's master when done. 

At any rate, what exists right now in the fork's master branch works and passes all the tests. 

Would appreciate merging this pull request. 


Thanks!

**Comment by seidnerj** [comment]
@oznu, can you please check this?

Thanks in advance

**Comment by oznu** [comment]
I'll review this soon. Quite busy with life at the moment sorry.

**Comment by seidnerj** [comment]
No worries. Thx.

**Comment by seidnerj** [comment]
Is there any way I can help getting this merged? Thanks.

**Comment by oznu** [comment]
Thanks for this, looks good, however a few things:

1. I think this should be an optional widget, the default layout should remain unchanged
2. the network utilisation tracking should not occur server side if the widget is not enabled - I can see certain low powered devices not liking the additional calls to check network activity every few seconds. Maybe only start the interval to check network activity when requested for the first time?

**Comment by seidnerj** [comment]
I've removed the network widget from the default layout. Regarding you second point, am happy to do that but I'm not sure how - could you please point me to a similar behavior in the existing code or provide some other guidance? Thanks in advance

**Comment by oznu** [comment]
@seidnerj if you don't mind rebasing to the current master to resolve the merge conflict, I'll merge this in and fix up that part before doing a release. 

If that works for you?

**Comment by seidnerj** [comment]
Strange issue with the tests. I've run the e2e tests locally and it finished successfully. I also launched and used the server successfully. Any idea what's the issue?

**Comment by oznu** [comment]
Made a few changes if you would like to take a look 😄 

4.43.0-test.7
https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

1. Increased default width of the widget.
2. Changed default position in mobile layout.
3. Changed units from MB/s to Mb/s - most users i think still measure their internet speed in Mb/s.
4. Polling will only start the first time the get network info method is called.

**Comment by seidnerj** [comment]
Looks great! Thanks a lot!

**Comment by oznu** [comment]
On second thoughts, maybe we should only poll for network activity when the client needs it. There is little point having 10 seconds worth of history.

**Comment by seidnerj** [comment]
Agreed. I guess this can be said about other stats as well.

**Pull request merged**
