### PR TITLE
Fix sidebar on mobile (beta)

### PR DESCRIPTION
**Pull request by mkz212**
- Fix sidebar on mobile. On iPhone it cuts sidebar when scrolling. 

https://github.com/user-attachments/assets/1886e293-0a83-426f-9b17-ac94d8599769

- Sidebar width 250px instead 210px.

### CODE REVIEW

**Comment by bwp91** [comment]
https://github.com/user-attachments/assets/f78bdae4-2204-4d33-9982-fc69400da721

**Comment by mkz212** [comment]
@bwp91 fixed

**Comment by bwp91** [comment]
something is still not quite right in mobile view.

the menu icons appear before the menu has fully expanded and it looks a little weird

**Comment by mkz212** [comment]
https://github.com/user-attachments/assets/98092e09-8120-44c1-ae86-eb4ba3a60c41

**Pull request merged**
