### PR TITLE
update de.json

### PR DESCRIPTION
**Pull request by Staubgeborener**
Update German translation (`de.json`)

### CODE REVIEW

**Comment by Staubgeborener** [comment]
Do not merge yet, I forgot some lines. I will do the rest within the next commit in like a few hours.

**Comment by donavanbecker** [comment]
> Do not merge yet, I forgot some lines. I will do the rest within the next commit in like a few hours.

converted the PR to draft. When ready click ready for review to remove the draft status.

**Comment by donavanbecker** [comment]
@Staubgeborener can you rebase this to the alpha branch? as we have more changes in that, that might need to be translated? and then we will move the change to the beta branch, before this is included in the next version.

**Comment by bwp91** [comment]
Hi @Staubgeborener i think this now might be very out of date.

Very grateful as always. Let's close this and when you have a free moment could you go through an updated `de.json` file and do your thing?!

Danke!

**Pull request closed without merging**
