### PR TITLE
Add messaging around backup files exceeding maximum restore size

### PR DESCRIPTION
**Pull request by NorthernMan54**
This is an implementation of messaging around backup files exceeding maximum restore size.   I put this together in an attempt to reduce the number of issues raised around file restores.

It also implements an initial pattern for globalDefaults, ie values that are leveraged in multiple locations within the UI and Server code base.

This adds two new translation message "backup.label_backup_size" and "backup.message_backup_exceeds_max_size"

image

### CODE REVIEW

**Comment by NorthernMan54** [comment]
Fails

  ● BackupController (e2e) › POST /backup/restore large backup

    expect(received).toBe(expected) // Object.is equality

    Expected: 201
    Received: 500

      340 |     });
      341 |
    > 342 |     expect(res.statusCode).toBe(201);
          |                            ^
      343 |
      344 |     await new Promise((r) => setTimeout(r, 100));
      345 |

      at Object.<anonymous> (test/e2e/backup.e2e-spec.ts:342:28)

**Comment by bwp91** [comment]
@NorthernMan54 if you take this test and run it from the beta branch, then for me it passes, so maybe this has been fixed in the beta version?

**Comment by NorthernMan54** [comment]
I was working with latest, so I just switched to base on the PR, and it showed as fixed.  I then increased the backup file size, and was able to recreate. Hopefully you are also able to recreate.

**Comment by bwp91** [comment]
Does it fail when the file is over 25mb?

https://github.com/homebridge/homebridge-config-ui-x/blob/eea2b9c793a028fceb49fc0ffcf4b651e294d944/src/main.ts#L32

**Comment by NorthernMan54** [comment]
@bwp91 I think I have figured it all out.   https://github.com/fastify/fastify-multipart is used to manage the restore upload, and we defined a maximum fileSize of 25 * 1024 * 1024 ( 25 MB ).  When a file larger than this is uploaded, the data is truncated, and triggers a ZLIB - unexpected end of file.

To reduce the noise around these issues, I have added two guard rails.

1 - A backup file that is larger than 25 * 1024 * 1024 ( 25 MB ), will trigger an error to the homebridge log file **_Backup file exceededs maximum restore file size 25mb_**.

2 - When doing a restore, if the upload is truncated ( exceeds the maximum fileSize ), the message **_Restore file exceeds maximum size 25MB_**

Originally I was going to cancel the backup, but that would be leave people without anything to work with.  So I figured just logging an error was more manageable.

**Review by donavanbecker — DISMISSED** [review]

**Review by donavanbecker — DISMISSED** [review]

**Review by donavanbecker — DISMISSED** [review]

**Review by donavanbecker — DISMISSED** [review]

**Review by donavanbecker — APPROVED** [review]

**Review by donavanbecker — DISMISSED** [review]

**Review by donavanbecker — DISMISSED** [review]

**Review by donavanbecker — DISMISSED** [review]

**Review by donavanbecker — DISMISSED** [review]

**Review by bwp91 — APPROVED** [review]
looks good! i don't mind to merge this now and then mess with the design separately, be good to try this out on my pi 👍

**Pull request merged**
