### PR TITLE
fix?

### PR DESCRIPTION
**Pull request by mkz212**
Let's see if it changes something?

### CODE REVIEW

**Review by donavanbecker — APPROVED** [review]

**Comment by donavanbecker** [comment]
Here is the fix!!!

**Comment by mkz212** [comment]
beta 66 still have this problem:

Zrzut ekranu 2023-11-9 o 16 23 58

**Comment by donavanbecker** [comment]
haven't had this issue.

**Comment by donavanbecker** [comment]
beta.68 is the fix. So should this be reverted?

**Comment by mkz212** [comment]
No . I just make new PR for this.

**Pull request merged**
