### PR TITLE
Create Ukrainian language ua.json

### PR DESCRIPTION
**Pull request by xrust83**
Adding the Ukrainian language

### CODE REVIEW

**Comment by xrust83** [comment]
Was my job of no use to anyone?

**Comment by oznu** [comment]
I'll merge this when i a chance. There are a few housekeeping things to do when adding a new language and if i merge now I'll forget about them 😄

**Comment by oznu** [comment]
Thanks!

**Comment by xrust83** [comment]
when you abbreviate Ukrainian, you indicated (uk), this is a mistake that is how the united kingdom is abbreviated. Ukraine shrinks like (ua)

ua

**Comment by oznu** [comment]
> when you abbreviate Ukrainian, you indicated (uk), this is a mistake that is how the united kingdom is abbreviated. Ukraine shrinks like (ua)

* uk is for the Ukrainian **language** as defined by [ISO 639-1](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
* UA is for the region of Ukraine as defined by [ISO 3166-1](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements)

**Comment by xrust83** [comment]
Country Ukraine - language Ukrainian

**Comment by oznu** [comment]
The text in the parentheses is the i18n language code - not the country.

**Comment by xrust83** [comment]
ok so be it. Thanks.
I found a typo. how can I correct it now? create a revision and open a new branch or what?

**Comment by oznu** [comment]
>  create a revision and open a new branch or what?

Yep, then a new PR 😄

**Comment by xrust83** [comment]
Please add the Ukrainian flag to the main page of the project, otherwise the Ukrainian language will be there soon and there will be no flag =)

**Pull request merged**
