### PR TITLE
latest <- beta

### PR DESCRIPTION
**Pull request by donavanbecker**
### UI Changes

- improve power options button display (#1961) (@mkz212)
- update credits modal with supporters
- add warning to remove-single-cached-accessory (#1985) (@mkz212)
- refactor backup and restore modals, separate items on settings page
- standardise modal sizes
- standardise warning sections on settings modals
- minor adjustments to settings page
- update icons on settings page (#1990) (@mkz212)
- break-word in plugin config (#1993) (@mkz212)
- Fix crash with missing homepage package.json property (#2013) (@regaw-leinad)
- improve ui of settings page (#2016) (@mkz212)
- improve ui of settings page (#2026) (@mkz212)
- remove mdns interface tooltips
- network interface widget: custom interface
- fix status widget graphs
- add 'report an issue' link to plugin menu
- configurable action button class on confirm component
- refactor widget settings view with styled checkboxes
- refactor accessory info view with styled checkboxes
- remove NPM/GitHub icons from plugin modals
- refactor user add/edit with styled checkboxes
- hide plugin logs menu item when plugin is disabled
- refactor add room button and modal

### Translation Changes

- updates to uk.json language file (#1978) (#1979) (@xrust83)
- updates to th.json language file (#1982) (@tomzt)
- updates to fr.json language file (#1991) (@SonnyT72)
- updates to ja.json language file (@yima0913)
- Correct slow restart message (#2006) (@jamieburchell)
- updates to es.json language file (#2020) (@AxelDreemurr)

### Other Changes

- improve GitHub actions
- fixed Environment Info selection on bug and support templates
- add wiki change request issue template
- removed force of earlier version of `bonjour-service` as a fix has been implemented in latest version 
- updated release drafter template so releases do not start with a `v`
- updated special plugin lists
- check local dir for homebridge when running dev
- dependency updates
- update `@homebridge/` dependencies
- standardise CHANGELOG to same as `homebridge`
- standardise README to same as other hb repos

### CODE REVIEW

**Comment by yima0913** [comment]
Updated Japanese translation file.
[ja.json](https://github.com/homebridge/homebridge-config-ui-x/files/14305364/ja.json)

**Comment by regaw-leinad** [comment]
couldn't find in any docs - what's the release cadence here for beta -> prod?

**Comment by NorthernMan54** [comment]
@regaw-leinad Not answering your question, but the beta release is automatically published if your interested in a new feature.

**Comment by regaw-leinad** [comment]
> @regaw-leinad Not answering your question, but the beta release is automatically published if your interested in a new feature.

thanks @NorthernMan54! I'm runnin on beta; just curious those non-beta users

**Review by bwp91 — APPROVED** [review]

**Pull request merged**
