### PR TITLE
Update nl.json

### PR DESCRIPTION
**Pull request by milo526**
Overhaul of dutch translations to be more natural.

### CODE REVIEW

**Comment by tooh** [comment]
Hi @milo526 
As author of the initial nl translation i’m happy that you improved on it.

I noticed some minor things. 

Like geblokeerd -> geblokkeerd
Accessories -> accessoires

And in general verb/noun use

**Comment by milo526** [comment]
> Hi @milo526
> As author of the initial nl translation i’m happy that you improved on it.
> 
> I noticed some minor things.
> 
> Like geblokeerd -> geblokkeerd
> Accessories -> accessoires
> 
> And in general verb/noun use

Hello,

Thank you!

Could you maybe request changes or suggest improvements where necessary?

**Comment by oznu** [comment]
Thanks

**Comment by dvanzoerlandt** [comment]
> Overhaul of dutch translations to be more natural.

Hi Milo,

Looks good, but I see some room for improvement. I would like to make an update.

For example, there are (and were) quite a few cases where compound words are erroneously written apart from each other, where they actually should have been written as one word. This is the so called "spatieziekte" in Dutch.

I'm not very used to attaching a file, where could I find instructions to do so?

**Pull request merged**
