### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by philippe317**
## :recycle: Current situation

Some texts were not translated

## :bulb: Proposed solution

Translation of English terms into French

### CODE REVIEW

**Review by donavanbecker — DISMISSED** [review]

**Comment by donavanbecker** [comment]
I have rebased this to the alpha branch, please resolve conflicts.

**Comment by SonnyT72** [comment]
Sorry to bother you guys but it seems to me that some of the modifications provided by this commit are already in 4.55.0. For my information, are we supposed to make our commits on the "latest" or the "alpha" branch?

**Comment by donavanbecker** [comment]
> Sorry to bother you guys but it seems to me that some of the modifications provided by this commit are already in 4.55.0. For my information, are we supposed to make our commits on the "latest" or the "alpha" branch?

In most cases, beta branch unless we  freeze it for a release that is being released.

**Comment by donavanbecker** [comment]
@philippe317 going to close this as we have an update version in the next version (4.55.1). If you see more updates that need to be made please open another PR.

**Pull request closed without merging**
