### PR TITLE
Small changes in widgets

### PR DESCRIPTION
**Pull request by mkz212**
### System info widget:
- change of order (e.g. time zone is not so important to be first).

Zrzut ekranu 2023-11-6 o 19 42 43

### Homebridge widget
- change of order (system started / not startet - first, Homebridge - second).
- Homebridge update information moved to the bottom line so that it is in accordance with the Plugins.
- adding the name Homebridge permanently.
- small corrections with margin and padding so that if someone wants this widget in a vertical version it will look better.
- change icon about update node: from info to circle-up.

Zrzut ekranu 2023-11-6 o 19 40 56

### QR code widget 
- Changing the text to a simpler one: "Skan to add to Homekit" (note: in some languages there is "Apple Home", and in some there is "Homekit").

### CODE REVIEW

**Comment by donavanbecker** [comment]
For the Homebridge widget, I think we should make this customizable if you are wanting it changed. Just like we have the `Display Port` option on this widget.

**Comment by mkz212** [comment]
I don't quite understand? What exactly you want to make customizable?

**Comment by donavanbecker** [comment]
> I don't quite understand? What exactly you want to make customizable?

The ordering of Homebridge, System, Plugin.

**Comment by mkz212** [comment]
What I still miss in system info:
- SSH and FTP : enabled / disabled, and info icon next to it and after click info how to SSH and how to conect via FTP.
- info about updates of packages (apt update)
- info about Homebridge Image version and latest image (check for update)
- there should be only storage path: configuration path and plugins path should be as a tooltip or after click on info icon next to storage path
- Number of bridges and devices:  E.G.: 3 / 41

Maybe option to choose what elements should be visible?

**Comment by bwp91** [comment]
In general I like the changes proposed here. 

A couple of things from me:

- Can we keep the `Scan this code with the camera on your iOS device to add to Apple Home.` text change out of this PR and perhaps include it in https://github.com/homebridge/homebridge-config-ui-x/pull/1641 PR?
- ~~There is a conflict in one of the files which needs updating~~
- Perhaps the homebridge version could go next to Homebridge so that the text below can simply say 'Up to date' to match the plugins item (to the right or below) - the version part can still be a link to the modal to change version
    Screenshot 2023-11-07 at 09 31 54

**Comment by mkz212** [comment]
- ok, I restored the original text under QR code.
- I changed as you advise (Homebridge v.1.7.0 in same line) I think it looks even better.

**Comment by donavanbecker** [comment]
@mkz212 Something got messed up with the plugin link. Even if you didn't have any updates, you could "up to date" under plugin and it would take you to the plugin screens

**Comment by bwp91** [comment]
this was me ^ i can add it back

**Comment by donavanbecker** [comment]
Sounds good thanks @bwp91!

**Pull request merged**
