### PR TITLE
replace nearly all "accessories" with "zubehör"

### PR DESCRIPTION
**Pull request by Staubgeborener**
Fixed some mistakes. 

What is the general consensus? Accessories = Zubehör? Do we use “Child-Bridge” or “Unter-Bridge” in german translation?

### CODE REVIEW

**Comment by bwp91** [comment]
@Staubgeborener do you want me to merge this or wait to see if it gets any comments to your questions?

**Comment by Staubgeborener** [comment]
I think we should wait, maybe someone else will come up with an opinion on this topic.

**Comment by Staubgeborener** [comment]
Btw, `de.json` is missing `"form.button_restore": "Restore"` (which should be `"form.button_restore": "Wiederherstellen",`), but we have something like `"backup.title_restore": "Wiederherstellen"` which isn't used anymore. Which leads to this:

image

Before I mess something up here, could you please correct this and bring `de.json` up to date? Then this PR could be merged.

Oh btw, what even is "History Items" in the network context?

image

**Comment by bwp91** [comment]
@Staubgeborener I updated your fork with the latest changes from the latest branch. You should see the 'missing' entries now.

Also History Items is how many historical data points appear on the network widget (similar config exists for memory and CPU widgets)

**Comment by Staubgeborener** [comment]
ready to merge @bwp91

**Review by bwp91 — APPROVED** [review]
Thanks!

**Pull request merged**
