### PR TITLE
Default widget layout

### PR DESCRIPTION
**Pull request by mkz212**
My last approach to default look suggestion.

Zrzut ekranu 2023-11-7 o 09 31 00

### CODE REVIEW

**Comment by bwp91** [comment]
Don't forget to bring that `scan to add to homekit` language change here, I like the idea of the text being shortened, but I will leave this PR for @donavanbecker as I know he has been putting some work into screenshots for widget layouts 👍

**Comment by mkz212** [comment]
I changed the text in all language versions (using Google translate).

**Review by donavanbecker — APPROVED** [review]

**Comment by donavanbecker** [comment]
Looks like something got messed up with the layout, I hit reset layout and got this:

Screenshot 2023-11-07 at 11 01 43 AM

**Comment by donavanbecker** [comment]
I will push a fix and see if it resolves it.

**Comment by grzegorz914** [comment]
Also on iPad portrait and landscape mode cut the widget.
IMG_0902
IMG_0901

**Comment by mkz212** [comment]
@donavanbecker I just updated code. Can You try? (Child Bridge Widget x position should be 15, not 16).

**Comment by donavanbecker** [comment]
@grzegorz914 does beta.25 fix it?

**Comment by mkz212** [comment]
I think that Homebridge widget should be scrollable (like System info widget).

**Comment by grzegorz914** [comment]
@donavanbecker  no, the problem still exist with b.25

**Comment by mkz212** [comment]
@donavanbecker Child Bridge Widget x position should be 15, not 16. And there is no "Homebridge" word , only version.

**Comment by donavanbecker** [comment]
okay, I updated what you had @mkz212. If that doesn't work. I am going to revert back to what I had and see if it resolves it.

**Comment by mkz212** [comment]
also need to add to /ui/src/scss/themes-dark.scss :

```
.dropdown-item, .dropdown-item:hover {
   color: #eeeeee;
}
```

to fix this:
Zrzut ekranu 2023-11-7 o 19 19 35

**Comment by donavanbecker** [comment]
that worked @mkz212.

@grzegorz914 beta.26. How is that for you?

**Comment by donavanbecker** [comment]
> also need to add to /ui/src/scss/themes-dark.scss :
> 
> ```
> .dropdown-item, .dropdown-item:hover {
>    color: #eeeeee;
> }
> ```
> 
> to fix this: Zrzut ekranu 2023-11-7 o 19 19 35

I think you meant to put this in a different PR right?

**Comment by mkz212** [comment]
- beta 26 fix layout. 

- Still no Homebridge word next to version in Homebridge widget.

Zrzut ekranu 2023-11-7 o 19 29 18


- also need to add to /ui/src/scss/themes-dark.scss :

```
.dropdown-item, .dropdown-item:hover {
   color: #eeeeee;
}
```

**Comment by grzegorz914** [comment]
@donavanbecker  b.26 nothing changed but I can rearrange it and adapted to the screen. looks like the size is only dynamic in x size and for y size is static.

**Comment by mkz212** [comment]
@donavanbecker I wouldn't want to mess up too much now. Could you add this code? 

to /ui/src/scss/themes-dark.scss :

```
.dropdown-item, .dropdown-item:hover {
   color: #eeeeee;
}
```

**Comment by mkz212** [comment]
@grzegorz914  I think that problem is because this widget is not scroled like the widget system info. In the last stable version, with such a layout as you present it also does not display correctly for me - the widget is simply too narrow for this.

**Comment by donavanbecker** [comment]
> @donavanbecker I wouldn't want to mess up too much now. Could you add this code?
> 
> to /ui/src/scss/themes-dark.scss :
> 
> ```
> .dropdown-item, .dropdown-item:hover {
>    color: #eeeeee;
> }
> ```

added for next beta.

**Comment by mkz212** [comment]
@donavanbecker 
- Maybe simple solution is change text: "Uruchomiony na porcie: 55555" to "Port: 55555". ? 
- Still no Homebridge word next to version. Can You fix this?

**Comment by bwp91** [comment]
do we need the word homebridge next to the version? the widget title is homebridge, is it not obvious? 
also with longer beta version names, having homebridge there too might push that column to be quite wide

**Comment by mkz212** [comment]
@bwp91 I thought it was a mistake. Ok. But I would change the text from: "Uruchomiony na porcie: 55555" to "Port: 55555". 

Zrzut ekranu 2023-11-7 o 19 50 35

**Comment by donavanbecker** [comment]
@mkz212, you have an option to hide that port also.

**Comment by mkz212** [comment]
And this can fix display of item:

Zrzut ekranu 2023-11-7 o 19 53 55


Every item need to have `mr-5 pr-5`

**Comment by mkz212** [comment]
> @mkz212, you have an option to hide that port also.

Yes, I know, But I think this text is too long and looks better just: `Port: 55555`

**Comment by mkz212** [comment]
@bwp91 @donavanbecker 

beta27 looks great. Only two changes in Homebridge widget:

- change text from Uruchomiony na porcie (Running on port) to simply `Port:` E.G. `Port: 12345`.
- to every item class add: `mr-5 pr-5`

Zrzut ekranu 2023-11-7 o 19 53 55


So it will change this:
Zrzut ekranu 2023-11-7 o 20 08 44

to this:
Zrzut ekranu 2023-11-7 o 20 09 46

**Comment by donavanbecker** [comment]
@mkz212, open a PR with these changes and I will merge

**Comment by mkz212** [comment]
beta 30 looks fantastic!

**Pull request merged**
