### PR TITLE
add "latestReleaseDate" property to HomebrigePlugin

### PR DESCRIPTION
**Pull request by mediter**
When a search returns multiple similar looking plugins, display the
latestReleaseDate might help people choose which plugin to use

add *ngIf="!plugin.installedVersion" to latestReleaseDate in ui

**Known Issue**
Currently, latestReleaseDate would also be shown for installed plugins, but package.json of installed plugins doesn't have "date" property

Ideally we could fetch this from npmjs.com registry, the response json has "date" property for each plugin

### CODE REVIEW

**Comment by oznu** [comment]
Thanks for the PR.

Are you able to update the plugin.service.ts file to only include the relevant changes - not the formatting updates?

**Comment by mediter** [comment]
Would this be okay? The reformatting might have been caused by a vscode extension. But I have disabled format on save, yet the editor still reformats the code on save. Quite odd.

**Comment by oznu** [comment]
Looking good now. Thanks.

I'll merge this soon.

**Comment by oznu** [comment]
I adjusted the display of this:

image

**Comment by oznu** [comment]
This is currently in beta, and will be release as part of v4.6.0.

You can install the beta now by running:

```
sudo npm install -g --unsafe-perm homebridge-config-ui-x@next
```

**Comment by mediter** [comment]
Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
