### PR TITLE
Default widget layout

### PR DESCRIPTION
**Pull request by mkz212**
Changing the default layout so that everything is visible, without having to scroll down.

Zrzut ekranu 2023-11-6 o 20 25 13

### CODE REVIEW

**Comment by donavanbecker** [comment]
I totally understand where you are coming from with having everything visible, but the child bridge widget is really small and most have a lot of plugins(child bridges).

Proposed change: make the QR Widget hidden if all bridges are paired.

**Comment by mkz212** [comment]
If someone has more bridges, they will simply enlarge this widget. According to me, the log widget should be visible because here new data still appears and in the bridge widget not.

The proposal with hiding the qr code somehow does not reach me - this qr is probably a some kind of homebridge "icon" and I got used to it, it gives character. Besides, the layout could break.

**Comment by mkz212** [comment]
Mayby this?

Zrzut ekranu 2023-11-6 o 22 29 51

Everything visible right away and a larger bridge widget.

**Comment by mkz212** [comment]
You can also make two default variants. One containing Bridges widget and second without it.

**Comment by donavanbecker** [comment]
I think we are going to stay with what we have.
default layout

**Comment by donavanbecker** [comment]
if you want to make other improvements that would allow it all to be on one page, feel free to open a PR for them.

**Pull request closed without merging**
