### PR TITLE
update de.json

### PR DESCRIPTION
**Pull request by Staubgeborener**
Update german translation

### CODE REVIEW

**Review by donavanbecker — APPROVED** [review]

**Comment by bwp91** [comment]
@Staubgeborener thanks!

Could you check one more thing for me here:
https://github.com/homebridge/homebridge-config-ui-x/pull/1626/commits/5e5d2a6b655d3ab0c317ea7bbb00a38f8c5af8d0

Where I have edited `de.json` does this make sense:

```
Vielen Dank für die Installation der {{ targetVersion }} Version von {{ pluginName }}
```

{{ targetVersion }} can be `latest` or `beta`

**Comment by Staubgeborener** [comment]
> Where I have edited `de.json` does this make sense:
> 
> 
> 
> ```
> 
> Vielen Dank für die Installation der {{ targetVersion }} Version von {{ pluginName }}
> 
> ```
> 
> 
> 
> {{ targetVersion }} can be `latest` or `beta`

German is both extremely flexible but also a very strict language at the same time. Very thankless, especially as we have to adopt some words directly from the english language, translate others and reinvent others.

For example 
`Vielen Dank für die Installation der beta Version von {{ pluginName }}`
Is working. More or less, I think the most of us prefer `Beta-Version` (so we just "create a new word"). 

But this one 
`Vielen Dank für die Installation der latest Version von {{ pluginName }}`
definitely don't work. No doubt. `latest` has to be translated to something like `aktuellsten`. Edit: the word `neuesten` which was used before is also okay but `aktuellsten` sounds more natural imo

**Comment by bwp91** [comment]
“latest” and “beta” are taken directly from the npm tags that plugins are published under. So not easy to translate these.

Perhaps I could add some formatting (would apply to all languages eg

Vielen Dank für die Installation der `latest` Version von {{ pluginName }}

? thanks for the info by the way.

**Comment by Staubgeborener** [comment]
Maybe by doing this in two steps, so putting the beta/latest version naming into braces after the "thanks for installation" sentence (which should work for all translations), and check the stuff before with an if-statement like 

`if (plugin.latestVersion?.includes('beta')) { ... } `

```html
<p class="text-center grey-text" [translate]="'plugins.manage.message_thanks_for_updating'">
        Thanks for installing  {{ pluginName }}
      </p>

<p class="text-center grey-text" [translate]="'plugins.manage.message_thanks_for_updating_version'"> ((Beta-)|(Aktuellste )Version)
      </p>

```

This would require two new translations for the i18n files: `latest` and `beta`. 

But in the end probably a bit much work, I think probably everyone of the german Homebridge users/community knows the meaning of "latest version".

**Pull request merged**
