### PR TITLE
Update layout.component.html

### PR DESCRIPTION
**Pull request by mkz212**
All the rest looks great!

### CODE REVIEW

**Comment by donavanbecker** [comment]
Screenshot 2023-11-07 at 5 04 22 PM

Was just going to post this. 

Are we good to merge?

**Comment by mkz212** [comment]
@donavanbecker What do you think about moving `Node.js Path` just under `Plugin Path`? So that all paths are side by side?

Zrzut ekranu 2023-11-8 o 00 08 35

**Comment by donavanbecker** [comment]
I think I would move all the other paths up to node.js path. so that node.js version is right above node.js path.

Also UI Settings needs to be corrected.

**Comment by mkz212** [comment]
I think it looks worse - so hard. Besides, I think these paths are less important than e.g. IP, etc.

Zrzut ekranu 2023-11-8 o 00 11 45


I would rather move Node Path below:
Zrzut ekranu 2023-11-8 o 00 08 35

**Comment by donavanbecker** [comment]
What about if we move Node.js version down as well?

**Comment by donavanbecker** [comment]
But let's wait till the next version to correct this. So we can get some testing done.

**Comment by mkz212** [comment]
It even looks good!

Zrzut ekranu 2023-11-8 o 00 18 11

**Comment by donavanbecker** [comment]
Okay get me a PR and we will push it out.

**Pull request closed without merging**
