### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by SonnyT72**
Add or Update translations on the following added or modified strings:
    ADDED:
        child_bridge.label_child_start
        child_bridge.label_child_stop
        menu.hbrestart.confirm_button
        menu.hbrestart.confirmation
        menu.hbrestart.title
        menu.linux.label_logs
        plugins.button_api_documentation
        plugins.button_homepage
        plugins.manage.child_bridge_button_restart_now
        plugins.manage.child_bridge_button_restart_now_one
        plugins.manage.child_bridge_restart_success
        plugins.manage.child_bridge_restart_failed
        plugins.manage.message_thanks_for_updating_restart_child_bridges
        plugins.manage.modal_verified_cta
        plugins.manage.modal_verified_message
        plugins.manage.modal_verified_title
        plugins.node_update_homebridge_ui_upgrade_and_try_again
        status.widget.systeminfo.label_disabled
        status.widget.systeminfo.label_enabled
        status.widget.systeminfo.label_glibc_warning
        status.widget.systeminfo.label_no
        status.widget.systeminfo.label_nodejs_path
        status.widget.systeminfo.label_yes
        status.widget.systeminfo.modal_glibc_cta
        status.widget.systeminfo.modal_glibc_message
        status.widget.systeminfo.modal_glibc_title
        status.widget.systeminfo.modal_servicemode_cta
        status.widget.systeminfo.modal_servicemode_message
        status.widget.systeminfo.modal_servicemode_title
    UPDATED:
        plugins.manage.message_thanks_for_updating_restart
        plugins.donate.message_learn_more
        status.message_code_scan_instructions

One inaccurate translation was also modified

## :recycle: Current situation

*Describe the current situation. Explain current problems, if there are any. Be as descriptive as possible (e.g., including examples or code snippets).*

## :bulb: Proposed solution

*Describe the proposed solution and changes. How does it affect the project? How does it affect the internal structure (e.g., refactorings)?*

## :gear: Release Notes

*Provide a summary of the changes or features from a user's point of view. If there are breaking changes, provide migration guides using code examples of the affected features.*

## :heavy_plus_sign: Additional Information
*If applicable, provide additional context in this section.*

### Testing

*Which tests were added? Which existing tests were adapted/changed? Which situations are covered, and what edge cases are missing?*

### Reviewer Nudging

*Where should the reviewer start? what is a good entry point?*

### CODE REVIEW

**Comment by donavanbecker** [comment]
@SonnyT72 Can you resolve conflicts?

**Comment by SonnyT72** [comment]
> @SonnyT72 Can you resolve conflicts?

I would like to but it looks like I can't because I don't have write acces on this repo.

**Comment by donavanbecker** [comment]
What should be accepted? I am guessing patch-3? Also looks like you may have 1 more line that needs updating.

```
<<<<< patch-3
    "menu.hbrestart.confirm_button": "Redémarrer Homebridge",
    "menu.hbrestart.confirmation": "Etes-vous sûr de vouloir redémarrer Homebridge?",
    "menu.hbrestart.title": "Redémarrer Homebridge",
=======
    "menu.hbrestart.confirm_button": "Restart Homebridge",
    "menu.hbrestart.confirm_service_button": "Restart HB Service & UI",
    "menu.hbrestart.confirmation": "Are you sure you want to restart Homebridge?",
    "menu.hbrestart.title": "Restart Homebridge",
>>>>>>> beta-4.52.3
```

New line:
```
"menu.hbrestart.confirm_service_button": "Restart HB Service & UI",
```

**Comment by SonnyT72** [comment]
I don't understand what happened, maybe is it because I should have translated the latest available l18n file in the beta branch instead of the latest branch? Can you please confirm?

Anyway, here are the correct translations (missing line) :

    "menu.hbrestart.confirm_button": "Redémarrer Homebridge",
    "menu.hbrestart.confirm_service_button": "Redémarrer HB Service et l'interface utilisateur",
    "menu.hbrestart.confirmation": "Etes-vous sûr de vouloir redémarrer Homebridge?",
    "menu.hbrestart.title": "Redémarrer Homebridge",

For the other translations, those in patch-3 are correct.

Sorry :/

**Comment by mkz212** [comment]
@SonnyT72 

It happened because a new line has been added in the meantime.

From `<<<<< patch-3` to `=====` is your code. 
From `=====` to `>>>>>>> beta-4.52.3` is updated code. 

You need to remove everything from `<<<<<` to `>>>>>>> beta-4.52.3` and place there updated code. 

In this case: 

```
"menu.hbrestart.confirm_button": "Redémarrer Homebridge",
"menu.hbrestart.confirm_service_button": "Redémarrer HB Service et l'interface utilisateur",
"menu.hbrestart.confirmation": "Etes-vous sûr de vouloir redémarrer Homebridge?",
"menu.hbrestart.title": "Redémarrer Homebridge",
```

**Comment by donavanbecker** [comment]
> I don't understand what happened, maybe is it because I should have translated the latest available l18n file in the beta branch instead of the latest branch? Can you please confirm?

Yeah I would always look for a beta branch in the future, first then go to latest. We will always try to merge to latest first to publish a beta to verify all is well first then push out a release.

**Comment by donavanbecker** [comment]
Sorry, a few more conflicts:

```
<<<<<<< patch-3
    "platform.version.title_service_restart_required": "Le redémarrage du service est requis",
    "plugins.button_api_documentation": "Documentation de l'API",
    "plugins.button_homepage": "Site du Plugin",
=======
    "platform.version.title_service_restart_required": "Le redémarrage est requis",
    "plugins.button_api_documentation": "API Documentation",
    "plugins.button_homepage": "Plugin Homepage",
>>>>>>> beta-4.52.4
```

```
<<<<<<< patch-3
    "plugins.manage.modal_verified_cta": "Plus d'informations",
    "plugins.manage.modal_verified_message": "Les Plugins d'Homebridge indiqués comme vérifiés ont fait l'objet d'une vérification par l'équipe du projet Homebridge afin de s'assurer qu'ils remplissaient différentes exigences encourageant les bonnes pratiques et une expérience utilisateur optimale.",
    "plugins.manage.modal_verified_title": "Plugins vérifiés",
=======
    "plugins.manage.modal_verified_cta": "More Info",
    "plugins.manage.modal_verified_message": "Homebridge plugins that are marked as verified have been reviewed by the Homebridge project team to ensure they meet various requirements that encourage best practices and a trouble-free user experience.",
    "plugins.manage.modal_verified_title": "Verified Plugins",
    "plugins.manage.plugin_logs": "View Plugin Logs",
>>>>>>> beta-4.52.4
```


So this line was added in the beta:
```
"plugins.manage.plugin_logs": "View Plugin Logs",
```

**Comment by donavanbecker** [comment]
I have resolved the conflicts, but you should verify all looks good and update that other new line.

**Comment by donavanbecker** [comment]
Thanks @SonnyT72

**Review by donavanbecker — APPROVED** [review]

**Pull request merged**
