### PR TITLE
small layout fix

### PR DESCRIPTION
**Pull request by mkz212**

### CODE REVIEW

**Comment by donavanbecker** [comment]
We will have to wait a little to merge this, but thanks!

**Review by donavanbecker — APPROVED** [review]

**Comment by mkz212** [comment]
- Something changed and now second menu on mobile is full with? 

- Logs is not translated. 

- UI Settings is Settings now?

IMG_4335

**Comment by donavanbecker** [comment]
> - Something changed and now second menu on mobile is full with? 
>

Not sure on this one, I haven't changed anything.


> - Logs is not translated. 
> 
> - UI Settings is Settings now?

Both of these need to be updated in the language files. UI was showing twice for English. So it was show UI UI Settings.

**Comment by mkz212** [comment]
Can I take care of it, if you want?

**Comment by donavanbecker** [comment]
Yes

**Comment by mkz212** [comment]
Simple option is change in en from "UI Settings" to "Settings" and add UI + translated settings.The question is whether the UI is supposed to be as untranslatable (as a plugin name?) Is it supposed to translate into other languages? (to be e.g.: Interface Settings etc.?).

**Comment by bwp91** [comment]
The translation should be “UI Settings”
There should be nothing else hardcoded to add to the translation

**Comment by mkz212** [comment]
Ok - So e.g. tranlation shoud be: UI Ustawienia or Interfejs Ustawienia?

**Comment by bwp91** [comment]
i don’t know what makes more sense in polish. but a lot of the other translations already have UI in them

**Comment by mkz212** [comment]
ok. why now i cannot simply update?

Zrzut ekranu 2023-11-8 o 06 51 46

**Comment by donavanbecker** [comment]
this is fixed in beta.43 but you will have to manually update.

**Comment by mkz212** [comment]
About this menu... Problem is width:

Zrzut ekranu 2023-11-8 o 07 08 20

There should be something like:

`max-width: 300px;`

or

`max-width: 70%;`

**Pull request merged**
