### PR TITLE
Fix menu on mobile

### PR DESCRIPTION
**Pull request by mkz212**

### CODE REVIEW

**Comment by bwp91** [comment]
Can you show a screenshot of the before and after change? thanks

**Comment by mkz212** [comment]
Now on mobile:
IMG_4337

**Comment by mkz212** [comment]
And after (on computer, because I don't have Inspector tool on iPhone):

Zrzut ekranu 2023-11-8 o 08 25 52

**Comment by mkz212** [comment]
Currently it is too wide and starts too high, which covers up the main menu

**Pull request merged**
