### PR TITLE
Update plugin-card.component.html

### PR DESCRIPTION
**Pull request by mkz212**
Zrzut_ekranu_2023-12-23_o_14 52 19
Zrzut_ekranu_2023-12-23_o_14 54 04

### CODE REVIEW

**Comment by mkz212** [comment]
@bwp91 I solved conflicts, last time!

**Comment by donavanbecker** [comment]
There are 7 commits for 1 file. Please squash commits

**Comment by mkz212** [comment]
@donavanbecker I don't know how, can you do it, please?

**Comment by donavanbecker** [comment]
using GitHub desktop you can combine commits by selecting all commits and squashing:

Screenshot 2023-12-28 at 10 45 27 AM

**Comment by bwp91** [comment]
Closing this as conflicts haven't been resolved _properly_ and is now quite out of date with the latest changes in beta branch

**Pull request closed without merging**
