### PR TITLE
Restart server / restart container 

### PR DESCRIPTION
**Pull request by mkz212**
@donavanbecker This option detects whether docker or not

### CODE REVIEW

**Comment by donavanbecker** [comment]
Can you please provide screenshots?

**Comment by mkz212** [comment]
Hmm. Not because I don't have it running locally. But it uses the same code as in the dropdown menu.

**Comment by donavanbecker** [comment]
@mkz212 We want to keep it, restart Homebridge instead of the container/machine. Now if you want to create a confirmation module that pops up to confirms restart of Homebridge. We would be up for that.

**Comment by mkz212** [comment]
@donavanbecker Sure, I will always be happy to help. But to make it right....

Currently on Raspberry Pi I have something like this:
Zrzut ekranu 2023-11-10 o 13 30 19

- Power button , without any confirmation restart server:
Zrzut ekranu 2023-11-10 o 13 31 43

- Restart server (in dropdown), show confirmation:
Zrzut ekranu 2023-11-10 o 13 32 32
and after confirmation show:
Zrzut ekranu 2023-11-10 o 13 32 57


Maybe there is a mistake here? Because here and here it is called as RESTART SERVER? (And in the case of power button it should be restart HOMEBRIDGE?).

**Comment by mkz212** [comment]
@donavanbecker Ok, I just checked and these are two different actions. Only bad translated (I added PR to improve it). I'm going to make a confirmation for RESTART HOMEBRIDGE (not server).

**Pull request closed without merging**
